name: CI-CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: stefanoeb/jest-action@1.0.4
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to EC2
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: bash deploy.sh
          username: ubuntu
          host: ${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
